
    # JDozerFuzzer - Microservicio de Discovery
    # Copyright (C) 2024 Cristián Saéz V.
    # Licencia: GNU AGPLv3 (ver LICENSE)
    
## Redis
jdozer.fuzzer.vectors.redis.uri=redis://${FUZZER_REDIS_HOST}:${FUZZER_REDIS_PORT}
jdozer.fuzzer.vectors.redis.stream.name=${FUZZER_BROKER_NAME}

quarkus.log.level=INFO
quarkus.log.category."jdozer.fuzzer".level=${FUZZER_LOG_LEVEL:INFO}
# quarkus.log.category."jdozer.fuzzer".enabled=true
quarkus.log.category."jdozer.fuzzer".min-level=${FUZZER_LOG_LEVEL:INFO}

